Repository Nuri1977/catalog-of-my-things, pull requests merged in 2022-04, with the labels that each got.

#25 Group task: Setup linters and rspec, add Item class ,and create console app entry-point.
  .github/workflows/linters.yml
  .github/workflows/test.yml
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  MIT.md
  README.md
  app/app.rb
  app/item.rb
  data/schema.sql
  main.rb
  spec/spec_helper.rb
Labels: enhancement

#26 Group task :Refactor console operation in separate module
  app/app.rb
  app/console.rb
  main.rb
Labels: documentation

#27 MusicAlbum and Genre classes
  app/genre.rb
  app/item.rb
  app/music_album.rb
Labels: enhancement

#30 Music and Genre method classes
  app/item.rb
  app/music_album.rb
Labels: enhancement

#35 Team meber 3: Implement methods for creating and listing Games with authors
  app/app.rb
  app/console.rb
  app/game_list.rb
Labels: enhancement

#36 Implement list music albums, genres and add music album options for console interactivty
  app/app.rb
  app/console.rb
  app/helper.rb
  app/music_list.rb
Labels: enhancement

#42 Music and Genre classes - Json
  app/app.rb
  app/genre.rb
  app/music_list.rb
  data/genres/genre.json
  data/genres/genre_crud.rb
  data/music/music.json
  data/music/music_album_crud.rb
Labels: enhancement

#43 Add options
  app/app.rb
  app/book.rb
  app/book_list.rb
  app/console.rb
  app/label.rb
  spec/book_label/book_spec.rb
  spec/book_label/label_spec.rb
Labels: enhancement

#44 Add SQL tables for Genres and Music Albums
  data/schema.sql
Labels: enhancement

#45 Preserve json
  app/app.rb
  app/book_list.rb
  data/books/book_crud.rb
  data/books/books.json
  data/labels/label_crud.rb
  data/labels/labels.json
Labels: enhancement

#46 Add schema for labels and books
  data/schema.sql
Labels: enhancement

#48 Group Task: Remove comments and style console prints better
  app/app.rb
  app/book_list.rb
  app/console.rb
  app/game_list.rb
  data/books/books.json
  data/games/games.json
  data/music/music.json
Labels: bug

#50 Fix music album test
  app/book.rb
  app/music_album.rb
  spec/book_label/book_spec.rb
  spec/music/music_spec.rb
Labels: bug
